# Generated by Django 6.0.3 on 2026-03-09 15:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag - inactive records are not deleted', verbose_name='Is Active')),
                ('session_key', models.CharField(blank=True, help_text='Session identifier for the cart', max_length=40, null=True, verbose_name='Session Key')),
                ('customer_name', models.CharField(blank=True, help_text='Optional customer name', max_length=200, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(blank=True, help_text='Optional customer email', max_length=254, verbose_name='Customer Email')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag - inactive records are not deleted', verbose_name='Is Active')),
                ('name', models.CharField(help_text='Name of the food item', max_length=200, unique=True, verbose_name='Food Name')),
                ('description', models.TextField(blank=True, help_text='Description of the food item', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the food item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price')),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('MAIN_COURSE', 'Main Course'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink'), ('SIDE_DISH', 'Side Dish')], default='MAIN_COURSE', help_text='Category of the food item', max_length=20, verbose_name='Category')),
                ('food_type', models.CharField(choices=[('REGULAR', 'Regular'), ('MEAL', 'Meal'), ('DRINK', 'Drink')], default='REGULAR', help_text='Type of food item', max_length=10, verbose_name='Food Type')),
                ('image', models.ImageField(blank=True, help_text='Image of the food item', null=True, upload_to='food_images/', verbose_name='Image')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the item is available for ordering', verbose_name='Is Available')),
                ('serving_size', models.PositiveIntegerField(blank=True, default=1, help_text='Number of servings', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Serving Size')),
                ('preparation_time', models.PositiveIntegerField(blank=True, default=30, help_text='Time to prepare in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Preparation Time (minutes)')),
                ('is_vegetarian', models.BooleanField(blank=True, default=False, help_text='Whether the meal is vegetarian', verbose_name='Is Vegetarian')),
                ('calories', models.PositiveIntegerField(blank=True, default=0, help_text='Calorie information', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calories')),
                ('drink_size', models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], help_text='Size of the drink', max_length=10, verbose_name='Drink Size')),
                ('is_alcoholic', models.BooleanField(blank=True, default=False, help_text='Whether the drink contains alcohol', verbose_name='Is Alcoholic')),
                ('volume_ml', models.PositiveIntegerField(blank=True, default=330, help_text='Volume in milliliters', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Volume (ml)')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag - inactive records are not deleted', verbose_name='Is Active')),
                ('order_number', models.CharField(help_text='Unique order identifier', max_length=20, unique=True, verbose_name='Order Number')),
                ('customer_name', models.CharField(help_text='Name of the customer', max_length=200, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(help_text='Email of the customer', max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(help_text='Phone number of the customer', max_length=20, verbose_name='Customer Phone')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the order', max_length=20, verbose_name='Status')),
                ('order_type', models.CharField(choices=[('BASIC', 'Basic'), ('ONLINE', 'Online')], default='BASIC', help_text='Type of order', max_length=10, verbose_name='Order Type')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for the order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount')),
                ('delivery_address', models.TextField(blank=True, help_text='Delivery address', verbose_name='Delivery Address')),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for the order', verbose_name='Special Instructions')),
                ('payment_method', models.CharField(blank=True, choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash on Delivery')], help_text='Method of payment', max_length=20, verbose_name='Payment Method')),
                ('payment_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], help_text='Status of the payment', max_length=20, verbose_name='Payment Status')),
                ('delivery_notes', models.TextField(blank=True, help_text='Additional delivery notes', verbose_name='Delivery Notes')),
                ('estimated_delivery_time', models.PositiveIntegerField(blank=True, default=45, help_text='Estimated delivery time', validators=[django.core.validators.MinValueValidator(15)], verbose_name='Estimated Delivery Time (minutes)')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the food item', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at the time of order', max_digits=10, verbose_name='Unit Price')),
                ('food_item', models.ForeignKey(help_text='The food item', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='foodapp.fooditem', verbose_name='Food Item')),
                ('order', models.ForeignKey(help_text='The order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodapp.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the item', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the item', verbose_name='Notes')),
                ('cart', models.ForeignKey(help_text='The cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='foodapp.cart', verbose_name='Cart')),
                ('food_item', models.ForeignKey(help_text='The food item being ordered', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='foodapp.fooditem', verbose_name='Food Item')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'unique_together': {('cart', 'food_item')},
            },
        ),
    ]
